"""add_google_id_and_nullable_password_to_users

Revision ID: 282a0255237c
Revises: b28c31f47d90
Create Date: 2026-09-07 12:32:26.284143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282a0255237c'
down_revision = 'b28c31f47d90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=128), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_users_google_id'), ['google_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_id'))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
