"""add shortlist_threshold to jobs

Revision ID: cb842f027255
Revises: a7c9e2f4b1d3
Create Date: 2026-09-09 12:19:59.077639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb842f027255'
down_revision = 'a7c9e2f4b1d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shortlist_threshold', sa.Integer(), server_default='40', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('shortlist_threshold')

    # ### end Alembic commands ###
